[package]
name = "wane_ui"
version = "0.17.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.2", features = ["bevy_ui", "bevy_ui_render", "bevy_log", "bevy_picking", "experimental_bevy_ui_widgets"], default-features = false }
wane_observers = { path = "../wane_observers"}
